### ISSUE TITLE
Exported video text is super low-resolution and distorted

### ISSUE THREAD

**Issue by joshuabardwell** [betaflight/blackbox-log-viewer#112]
Steps to reproduce: export video. In the resulting .webm file, the text showing the stick positions and frame number is super low-resolution and distorted. I have verified this at both 1080 and 720 export. See screen shot:

![image](https://user-images.githubusercontent.com/8303366/36498157-7aaaeb2e-170b-11e8-8aa5-bb45f438e138.png)

**Comment by wolkesson** [comment]
I've recently made some changes to the stick rendering and at least it now works on my log files. @joshuabardwell: Could you please check if the latest version has fixed the problem? You'll have to compile from code. Or if you like, you could post some files here and specify your user and export settings and I'll test it for you.

**Comment by McGiverGim** [comment]
You can grab the latest version from here too http://andwho.sytes.net:8080

I think remember this only happens when you have no video, only log. Have you tested it without video @wolkesson ?

**Comment by wolkesson** [comment]
The bug is still present when exporting just the log. I’ll look into it!

**Comment by McGiverGim** [comment]
This does not seem easy... Good luck! 😊

**Comment by wolkesson** [comment]
Hum, it had nothing to do with the canvas size, render quality or resolution (devicePixelRatio nor backingStorePixelRatio). The "export canvas" looked good if added to the visible DOM. Also the resolution of for example the mode text inside the sticks is good. So I suspect it has something to do with webm-writer not liking transperency.

Since my knowledge of webm is limited, I've created a work-around in PR #194 by instead of clearing the canvas (with transperent color) I fill it with black.
