### ISSUE TITLE
RC command traces (RPY) do not display correctly in newest master

### ISSUE THREAD

**Issue by flint723** [betaflight/blackbox-log-viewer#177]
Newest master 1564f98 (probably older ones too) has the issue, RPY traces are off the bottom of the chart.  I think it's just an BBE error because the values (1000-2000 scale) appear correctly in the legend area.  Throttle works fine.

Edit: Adjusting zoom on throttle graph does make RPY traces appear correctly.
![image](https://user-images.githubusercontent.com/30608240/40159513-41ebb31c-596f-11e8-8000-52de547cfa64.png)

**Comment by McGiverGim** [comment]
I have done some tests:
- This only happens when the "RC Commands" group is selected if the Graph setup.
- If after that, you enter in the graph setup again, the group has disappeared and shows the individual graphs. Pressing saving fixes the issue.
- Another option is to select each of the graphs individually, then the bug does not happen.

I suppose some value to adjust the individual graphs is ignored when selecting the group.
