### ISSUE TITLE
Stick Display - Top is cut off (tested with build 72)

### ISSUE THREAD

**Issue by Lord-Quake** [betaflight/blackbox-log-viewer#195]
It doesn't matter where it is positioned and what size it has.
![stick_window](https://user-images.githubusercontent.com/29223282/40890104-10c227ac-6771-11e8-984f-cee46e6814ea.png)

**Comment by McGiverGim** [comment]
@wolkesson maybe something here https://github.com/betaflight/blackbox-log-viewer/pull/188 can have this secondary effect?

**Comment by Lord-Quake** [comment]
Maybe this is also related?
![time_stamp](https://user-images.githubusercontent.com/29223282/40890192-793cf5a4-6772-11e8-9e67-cb309dbea76a.png)

**Comment by McGiverGim** [comment]
Strange. The time is not cut in my screen.

**Comment by Lord-Quake** [comment]
This is on a different computer. It seems to be placing itself randomly.
![time_shift](https://user-images.githubusercontent.com/29223282/40912960-5c88db0e-67f3-11e8-971c-d7a6d807d322.png)

**Comment by wolkesson** [comment]
Sorry, I won't have time to look at this in the nearest days. There might be some side effect to my changes. 

The Square behide sticks and white axis are drawn with a side of 2*R, where R = Math.min(width/4 - 8, height/2 - 8). Stick position is in range [-1,1] is scaled with the same R. So it's not a simple scaling error. There could be a problem with the lookup table pitchStickCurve.lookup(), if it doesn't output in the range [-1,1]. Didn't the rccommand change too in #180 and #190? 

But I would say it's more likely a problem with the resize code, because of the time text positioning error. Do you get any console output errors?

I'm unable to reproduce. Can you post a log here?

**Comment by Lord-Quake** [comment]
No worries. This is only a cosmetical problem.
Here another screen shot of what I mean when I say the top is cut off.
It looks like a resizing issue. Example:
![resize_1](https://user-images.githubusercontent.com/29223282/40957190-36c45a3c-6894-11e8-94b9-995d388346a4.png)
![resize_2](https://user-images.githubusercontent.com/29223282/40957618-3e40ba1a-6896-11e8-8977-1516469118db.png)

I cannot always reproduce the text positioning error problem. It happens 'randomly'.

**Comment by McGiverGim** [comment]
Changing the height of the canvas seems to fix the issue. 
I will check the code to see where this height is calculated.

**Comment by Lord-Quake** [comment]
Today it showed up at this position:
![timestamp](https://user-images.githubusercontent.com/29223282/41020480-5677324e-6963-11e8-9055-f2fd602b1cfb.png)

**Comment by McGiverGim** [comment]
@Lord-Quake can you open a new issue with the "time" problem? This issue with the sticks has been fixed and closed, if the other still remains, please open a new issue and I will try to reproduce it and fix.
