### ISSUE TITLE
Betaflight Blackbox Explorer crashes 

### ISSUE THREAD

**Issue by jasenhowell** [betaflight/blackbox-log-viewer#282]
Betaflight Blackbox Explorer crashes after 2 seconds of playing  log or moving along the quick access bar. any ideas?

**Comment by mikeller** [comment]
@jasenhowell: I have got an idea: How about you supply a bit more information, like what version of the Blackbox Log Viewer you are using, and the log file / video that you have opened when this is happening?

**Comment by jasenhowell** [comment]
here is the link to the video   
https://youtu.be/HartWlsjCys

**Comment by jasenhowell** [comment]
[https://1drv.ms/u/s!AsgLZPDv54KstHR0zWtulDtIr65-](url)

**Comment by jasenhowell** [comment]
version 3.2.0

**Comment by mikeller** [comment]
I can reproduce the problem in 3.2.0, and it looks like it's the one that was fixed in #246. As a confirmation, the problem is fixed in the latest version from `master`, which will be released as 3.3.0 within a few weeks.

On a side note, your log has a lot of dropouts. You might want to look into reducing the logging rate.
