### ISSUE TITLE
Advances User Settings: Buttons not visible if Watermark is ON

### ISSUE THREAD

**Issue by mrRobot62** [betaflight/blackbox-log-viewer#372]
Behaviour:
MacOS Mojave 10.14.06, MacBook Pro, 13" Retina Display
BBE: 3.4.0

Advanced User Settings:

If slider "Watermark" is ON, windows size expand on Y-Size out of screen, with result, that buttons are not longer visible. Window is not movable.

<img width="953" alt="BBF_3 4 0_Issue01" src="https://user-images.githubusercontent.com/949032/66026971-43164280-e4fa-11e9-9ff2-ee9f6deb3a71.png">

<img width="982" alt="BBF_3 4 0_Issue00" src="https://user-images.githubusercontent.com/949032/66027132-8c669200-e4fa-11e9-9eeb-97723b37c11f.png">

BTW: I built a mac dmg file for 3.4.0 - is it possible to upload this file for other mac-users.
3.4.0 is interesting, because a noise-plot is now available :-)

**Comment by mikeller** [comment]
@mrRobot62: BTW: I built a mac dmg file for 3.4.0 - is it possible to upload this file for other mac-users.

Sure, feel free to add it here - or add a link to version shared on Google Drive or dropbox if it is too large.

We currently do not have a CI set up that is capable of building and publishing a MacOS installer for all changes to `master` - this is due to the fact that it is only buildable on MacOS, and us not having a suitable MacOS CI server.

**Comment by mrRobot62** [comment]
I uploaded the dmg-file on my google-drive

[https://drive.google.com/open?id=1B5tEjiLgjrrAfoe9cAklr0UqW1_kekMt](url).

If needed, I can create dmg-files on my MacBookPro for you :-) - send me a notice -

**Comment by mrRobot62** [comment]
Bug fixed in 3.5.0RC1
