### ISSUE TITLE
graphs not working on Mac OS (10.15.5)

### ISSUE THREAD

**Issue by sweebee** [betaflight/blackbox-log-viewer#458]
If I run the explorer on my Mac, I cant see any graphs. On windows it works fine. I see the following:

<img width="1678" alt="Schermafbeelding 2020-07-22 om 07 55 42" src="https://user-images.githubusercontent.com/10496485/88139895-ed2d9b00-cbf0-11ea-9734-3ab5ac029085.png">

**Comment by SamSpiri** [comment]
same here on linux. I tried to downgrade to 3.4.0 and to 3.3.1 with no luck.
then being on 3.3.1 I tried to touch "Graph setup" button. Then in a window just after Axis Label there is a dropbox with the number "1". I changed that to "2" and since then I can see the graphs. So then I launched the latest version and graphs were already there I didn't touch settings.
