### ISSUE TITLE
Feature Request: Send MSP motor updates when replaying a log - Bounty attached

### ISSUE THREAD

**Issue by SgtDimes** [betaflight/blackbox-log-viewer#470]
**Is your feature request related to a problem?**

I have built a static test stand to qualify new craft before flight. I would like to be able to replay motor output through an armed quad secured to the stand for testing. 

**Describe the solution you'd like** 

It was suggested that sending MSP motor updates while replaying a log file using Black Box Viewer could work.

Open to suggestions and other solutions. 

To kisckstart this feature I have attached a bounty. Love the work you guys do, thank you! 

https://www.bountysource.com/issues/92712686-send-msp-motor-updates-when-replaying-a-log-bounty-attached

**Comment by wolkesson** [comment]
The Black Box Viewer is never connected to the aircraft. The log files are downloaded in other software (for example Betaflight Configurator) and just viewed here, hence the name. To replay motor control data one would have to have a connection to the autopilot and replay data at a very high and consistent speed. 

I would say that this is technically not possible on a non-realtime operating system. Especially if you want to use it to qualify an aircraft. This feature would have to be implemented in the Betaflight firmware, or one could build a separate firmware for this purpose. One problem with qualifying motors this way would be that since the airflow around the propellers are not there, the engine response will be very different. Resulting RPM from a given control output is not proportional, that is why Betaflight has RPM telemetry from the ESCs. 

I think you should post this issue and bouty in the Betaflight firmware repo instead and you might get better response (https://github.com/betaflight/betaflight). Or try their slack channel first (https://slack.betaflight.com/).
