### ISSUE TITLE
Feature Request: Store log file and video file and log sync time in exported workspace

### ISSUE THREAD

**Issue by joshuabardwell** [betaflight/blackbox-log-viewer#50]
Re-loading the workspace would then re-load the files exactly as they were. Suggest trying to locate the files based on both absolute path and searching in the same folder as the .json file.

**Comment by GaryKeeble** [comment]
Joshua, this is a really good idea; definitely needs adding as a feature; will add it to my todo list.

I've been thinking along the same lines for a while but in a slightly different way; I was trying to add the log file as a new track on the original video file so that you only needed to keep the video; when opened in a normal video player, it would just play normally; when opening it in the bb viewer, then it would find all the extended information of the log file and show it (a bit like exif information stored in photos); but I could never get it to work (just not got the skills) :-(

Regards.
