### ISSUE TITLE
Incorrect current value in bfl log exported from firmware 3.1.6

### ISSUE THREAD

**Issue by xlla** [betaflight/blackbox-log-viewer#52]
I am use blackbox explorer v2.5.10.
FC, brf3
battery, 4s
quad, 4 motors

after flash firmware 3.1.6 and restore settings, I found current_meter_scale is missing, so I add current scale in GUI direct, then I found it was renamed to ibat_scale.

I take a test flight, export log, found a very high measured current
<img width="1170" alt="screen shot 2017-03-18 at 20 43 37" src="https://cloud.githubusercontent.com/assets/3354817/24109017/60f56268-0dca-11e7-9c96-109251cbdeaa.png">
with same parameter in version 3.0.0 , it's correct.
<img width="900" alt="screen shot 2017-03-18 at 22 06 46" src="https://cloud.githubusercontent.com/assets/3354817/24109203/e2b39f36-0dca-11e7-8105-6763eb76ad09.png">

If I open the old log file generated by Betaflight v3.0.0, it just show correct current value, see second picture I posted.
So, I think Blackbox log viewer is fine, Or there is something wrong in BFL log format, In v3.0.0, exported log was TXT format.

**Comment by Turismo05** [comment]
This is the same for me on 3.16. showing over 100amps when it should be around 6.

**Comment by McGiverGim** [comment]
As far as I know, the value changed from 3.1.0. The correct value is the actual value divided into 10, so if you have 100 amps, the real value will be 10 amps. The master branch of Cleanflight Blackbox Low Viewer has a correction to show this correctly. 

Can you install manually the master branch of Cleanflight Blackbox Log Viewer to see if the issue is solved?
https://github.com/cleanflight/blackbox-log-viewer

Betaflight Blackbox Log Viewer will surely include this correction in a future, but I don't know when.

**Comment by xlla** [comment]
@McGiverGim yes, after install manually the master brach of Betaflight Blackbox Log Viewer, this issue was gone.
