### ISSUE TITLE
Newer builds of 3.6 Not Win7 Compatible

### ISSUE THREAD

**Issue by BrandonsBakedBeans** [betaflight/blackbox-log-viewer#548]
Win7 and ChromeOS on ARM is all I work with currently. I can't see the updated headers from 4.3 logs easily and the FFT charts don't display filters properly on the old build of 3.6 BBE I'm using. New nightly doesn't install on Win7.

**Comment by haslinghuis** [comment]
Windows 7 is EOL for almost 2 years now. Please see: https://www.microsoft.com/en-us/windows/windows-7-end-of-life-support-information.

We now only offer 64 bit builds for Windows.

Please also see: https://github.com/betaflight/betaflight-configurator#windows-users

**Comment by haslinghuis** [comment]
Does this install: https://github.com/betaflight/blackbox-log-viewer-nightlies/releases/tag/v20211029.4376

**Comment by BrandonsBakedBeans** [comment]
> Does this install: https://github.com/betaflight/blackbox-log-viewer-nightlies/releases/tag/v20211029.4376

No it does not. I get an error with the description "This program does not support the version of Windows your computer is running"

If I have it installed on a win10 machine and copy the install directory it runs fine on win7-64bit

**Comment by haslinghuis** [comment]
And this one: https://github.com/betaflight/blackbox-log-viewer-nightlies/releases/tag/v20210811.3500
(reverts NW.js 0.54.0 to 0.50.2, previous version was reverting to NW.js 0.54.0 from 0.54.1).

**Comment by McGiverGim** [comment]
It is not a problem of the NW version, is a restriction we add to the installer. 

https://github.com/betaflight/blackbox-log-viewer/blob/5eed5dacfee687a1da5a9a7fa9bd94c0836f86f0/assets/windows/installer.iss#L65

This was done to be in line with the Configurator, because the NW version that we use is not compatible with Win7 and some features that the Configurator need, more info here: https://github.com/betaflight/betaflight-configurator/issues/2131

As a workaround, I think we can add the portable version like we add in the Configurator:
https://github.com/betaflight/betaflight-configurator/pull/2739
and you can use it in unsupported systems but without support for part of Betaflight.
https://github.com/betaflight/blackbox-log-viewer/blob/5eed5dacfee687a1da5a9a7fa9bd94c0836f86f0/assets/windows/installer.iss#L65

Another option is to remove the limitation in the installer, but I think is a good idea to have the same minimum requirements in all the Betaflight products.
