### ISSUE TITLE
Add RPM in BBE data panel of eRPM (like previous with RPM)

### ISSUE THREAD

**Issue by SupaflyFPV** [betaflight/blackbox-log-viewer#667]
### Is your feature request related to a problem? Please describe

Previous RPM data in BBE had the RPM number in the info panel - can we add this for eRPM also?

<img width="1728" alt="Screenshot 2023-11-20 at 20 42 54" src="https://github.com/betaflight/blackbox-log-viewer/assets/46397720/1cdf191a-72c2-4e39-9880-c58d5ee257eb">

### Describe the solution you'd like

RPM number

### Describe alternatives you've considered

Using old RPM

**Comment by nerdCopter** [comment]
@tbolin

**Comment by tbolin** [comment]
@SupaflyFPV  This should already be implemented with https://github.com/betaflight/blackbox-log-viewer/pull/640 and https://github.com/betaflight/blackbox-log-viewer/pull/666.
Recently the name of the eRPM field was changed from `eRPM/100` to just `eRPM`, in https://github.com/betaflight/betaflight/pull/13123.
I made the adjustment to black box explorer in https://github.com/betaflight/blackbox-log-viewer/pull/666. 
However, for some reason there haven't been any nightly releases since that PR was merged 2 weeks ago.

(Alos note: There are no BF release where the field is called `eRPM/100`, so I decided to scrap backwards compatibility. 
The eRPM data in logs from before the field was renamed will not be properly formatted when using black box explorer nightlies released after https://github.com/betaflight/blackbox-log-viewer/pull/666.)

**Comment by SupaflyFPV** [comment]
> @SupaflyFPV This should already be implemented with #640 and #666. Recently the name of the eRPM field was changed from `eRPM/100` to just `eRPM`, in [betaflight/betaflight#13123](https://github.com/betaflight/betaflight/pull/13123). I made the adjustment to black box explorer in #666. However, for some reason there haven't been any nightly releases since that PR was merged 2 weeks ago.
> 
> (Alos note: There are no BF release where the field is called `eRPM/100`, so I decided to scrap backwards compatibility. The eRPM data in logs from before the field was renamed will not be properly formatted when using black box explorer nightlies released after #666.)

ah cool thanks for this...ok I guess I'll wait for an updated nightly...can we push it thru?

**Comment by haslinghuis** [comment]
Tried to build but there is a problem with appdmg dependencies (ds-store -> macos-alias) which is needed for OSX.

![image](https://github.com/betaflight/blackbox-log-viewer/assets/8344830/31872a9e-4a3e-40b9-a9ac-b808d04cb128)

![image](https://github.com/betaflight/blackbox-log-viewer/assets/8344830/8d0733b1-7c29-41f9-be3a-20d7c995ea2e)

**Comment by haslinghuis** [comment]
@McGiverGim @asizon We need someone with OSX to update ???

![image](https://github.com/betaflight/blackbox-log-viewer/assets/8344830/528b8885-db0e-45b3-8092-b67c14482783)

**Comment by haslinghuis** [comment]
CI builds has been fixed.
